name: Bug Report
description: File a bug report to help us improve the Mason Recipes website
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is
      placeholder: e.g., The search function doesn't return results when...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: e.g., The search should return 5 results

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: e.g., The search returned 0 results

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 120, Safari 17, Firefox 121

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you on?
      placeholder: e.g., Windows 11, macOS 14, iOS 17

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: If applicable, add screenshots to show the issue
      placeholder: Paste or drag screenshots here

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (optional)
      description: Any other information that might be helpful
      placeholder: e.g., Started happening after recent update...

  - type: input
    id: contact
    attributes:
      label: Contact (optional)
      description: How can we reach you?
      placeholder: ex: email@example.com